Tests/SendConsignments/SendInternationalShipmentTest.php
Tests/SplitStreet/InternationalFullStreetTest.php
src/Helper/MyParcelCollection.php
src/Helper/MyParcelCurl.php
src/Model/MyParcelConsignment.php
src/Model/MyParcelRequest.php
src/Model/Repository/MyParcelConsignmentRepository.php

@reindert-vetter requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/myparcelnl/sdk/

Scrutinizer Auto-Fixes

---

src/Model/Repository/MyParcelConsignmentRepository.php

Data being returned by the api no longer uses pickup_postal_code but postal_code instead.

Fixed setting the pick up fields. 

---

src/Helper/MyParcelCollection.php
src/Helper/MyParcelCurl.php

Removed a few unused/unnecessary functions and variables

MY-7464 cleanup sdk

---

src/Model/MyParcelConsignment.php

add street additional info variable and setter and modified related getter

Add street additional info setter 

---

composer.json
src/Concerns/HasCheckoutFields.php
src/Model/MyParcelCustomsItem.php

HotFix for customs description chars limit to 47 + ... otherwise the labels doesn't create

HotFix for customs description chars limit

---

composer.json
src/Concerns/HasCheckoutFields.php

Solved error: `Uncaught TypeError: json_decode() expects parameter 1 to be string, null given in /data/web/current/vendor/myparcelnl/sdk/src/Concerns/HasCheckoutFields.php:43`

Greate concept from backend magento

---

src/Adapter/DeliveryOptions/AbstractShipmentOptionsAdapter.php
src/Model/Consignment/AbstractConsignment.php
src/Services/ConsignmentEncode.php

feedback from https://github.com/myparcelbe/woocommerce/pull/102

Feedback from other pull request

---

Tests/SendConsignments/SendCooledDeliveryTest.php
src/Adapter/ConsignmentAdapter.php
src/Adapter/DeliveryOptions/AbstractShipmentOptionsAdapter.php
src/Adapter/DeliveryOptions/ShipmentOptionsV3Adapter.php
src/Model/Consignment/AbstractConsignment.php
src/Model/Consignment/PostNLConsignment.php
src/Services/ConsignmentEncode.php

Support cooled delivery

---

src/Adapter/ConsignmentAdapter.php
src/Adapter/DeliveryOptions/AbstractPickupLocationAdapter.php
src/Adapter/DeliveryOptions/PickupLocationV2Adapter.php
src/Adapter/DeliveryOptions/PickupLocationV3Adapter.php
src/Model/Consignment/AbstractConsignment.php
src/Model/Consignment/BpostConsignment.php
src/Model/Consignment/DPDConsignment.php
src/Model/Consignment/PostNLConsignment.php
src/Services/ConsignmentEncode.php

pickup_network_id does not exist and you will not get it back from the delivery_options but retail_network_id does.

pickup_network_id does exist

---

src/Adapter/DeliveryOptions/AbstractDeliveryOptionsAdapter.php
src/Adapter/DeliveryOptions/AbstractPickupLocationAdapter.php

- check pickupLocation and shipmentOptions are not null before calling toArray

fix: add toArray function to pickupLocationAdapters

---

src/Model/Consignment/AbstractConsignment.php

fix(regression): silently ignore disallowed options on consignments

---

src/Rule/Consignment/DeliveryDateRule.php

Fixes error when trying to create pickup shipments with bpost and dpd

fix(consignment): only validate delivery date if needed

---

src/Model/MyParcelCustomsItem.php
src/Services/ConsignmentEncode.php

regression, gezien het stuk is gegaan in #358 😬

regression(consignment): fix errors with row shipments

---

test/Bootstrap/ConsignmentTestCase.php
test/Model/Consignment/ConsignmentShipmentOptionsTest.php

test(consignment): fix mailbox shipment options test

---

src/03.reference/01.models.md

docs(models): add street_additional_info

---

src/Support/Collection.php

refactor(php8): remove deprecation warnings

---

src/Model/Consignment/HasPickupLocation.php

fix: allow null as pickup location country

---

src/Model/Consignment/AbstractConsignment.php

fix(consignment): add croatian country code

---

src/Collection/Fulfilment/OrderCollection.php
test/Model/Consignment/ConsignmentShipmentOptionsTest.php
test/Model/Consignment/PostNLConsignmentTest.php
test/Model/Fulfilment/OrderCollectionTest.php

fix(fulfilment): export physical properties

---

src/Model/Consignment/AbstractConsignment.php
src/Services/ConsignmentEncode.php
test/Model/Consignment/AbstractConsignmentTest.php
test/Model/Consignment/UPSConsignmentTest.php

feat(consignment): add state property

---

src/Adapter/ConsignmentAdapter.php
src/Adapter/DeliveryOptions/PickupLocationV3Adapter.php

fix: retail_network_id null value found

---

src/Model/Consignment/DPDConsignment.php

fix: remove dpd default weight

---

src/Collection/Fulfilment/OrderCollection.php
src/Model/Fulfilment/AbstractOrder.php
src/Model/PhysicalProperties.php
src/Services/ConsignmentEncode.php
test/Model/PhysicalProperties/PhysicalPropertiesTest.php

feat: add physical properties properly

---

src/Model/Consignment/AbstractConsignment.php
src/Model/Consignment/DHLEuroplusConsignment.php
src/Model/Consignment/DHLForYouConsignment.php
src/Model/Consignment/DHLParcelConnectConsignment.php
src/Model/Consignment/PostNLConsignment.php
src/Services/CountryCodes.php
src/Services/CountryService.php

feat: add row insurance possibilities

---

src/Rule/Consignment/MinimumItemValueRule.php
test/Rule/MinimumItemValueRuleTest.php

fix: prevent adding array to int calculating total value

---

src/Helper/ValidateStreet.php
test/Model/Consignment/ConsignmentSplitStreetTest.php

fix(splitstreet): ensure box separator for be address

---

src/Services/ConsignmentEncode.php

fix: resolve error for small package BE creation

---

src/Services/ConsignmentEncode.php

fix: fix error physical properties DHLForYou

---

src/Model/Consignment/DHLForYouConsignment.php

feat: allow small package with DHLForYou

---

src/Helper/ValidateStreet.php
test/Model/Consignment/ConsignmentSplitStreetTest.php

fix: support capital letters in box number detection

---

src/Adapter/ConsignmentAdapter.php
src/Adapter/DeliveryOptions/AbstractShipmentOptionsAdapter.php
src/Adapter/DeliveryOptions/ShipmentOptionsV3Adapter.php
src/Collection/Fulfilment/OrderCollection.php
src/Model/Consignment/AbstractConsignment.php
src/Model/Consignment/UPSConsignment.php
src/Services/ConsignmentEncode.php

feat(carriers): add ups shipping options

---

src/Model/Consignment/DHLForYouConsignment.php

feat: Allow saturday delivery for DHLForYou

---

.github/workflows/--test.yml
composer.json
docker-compose.yml
test/Model/Consignment/DHLParcelConnectConsignmentTest.php

fix errors running phpunit with coverage enabled and run tests on the lowest supported PHP version
resolves INT-743

test: fix errors running phpunit with coverage

---

src/Model/MyParcelCustomsItem.php

fix: allow leading zero for hs code classification

---

src/Model/Consignment/AbstractConsignment.php
src/Model/Consignment/PostNLConsignment.php
src/Model/MyParcelRequest.php
src/Model/PrinterlessReturnRequest.php
src/Services/ConsignmentEncode.php
test/Model/Consignment/ConsignmentShipmentOptionsTest.php

feat: support printerless return
